[module]

[module.hugoVersion]
extended = true
min = "0.84.0"

[[module.mounts]]
source = "content"
target = "content"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.imports]]
path = "github.com/twbs/icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[module.imports.mounts]]
source = "icons"
target = "assets/libs/bootstrap-icons"
